[package]
name = "znicz-tui"
version.workspace = true
edition.workspace = true
license.workspace = true
authors.workspace = true
rust-version.workspace = true

[dependencies]
znicz-core = { path = "../znicz-core" }
znicz-library = { path = "../znicz-library" }
ratatui.workspace = true
crossterm.workspace = true
crossbeam-channel.workspace = true
tracing.workspace = true
color-eyre.workspace = true
